using AutoFixture.Xunit2;
using FluentAssertions;
using Xunit;

namespace Explore.AutoFixture.Test
{
    public class AutoFixtureXUnitLibShould
    {
        [Theory]
        [AutoData]
        public void Return_Autogenerated_Primitive_Value(int integer) => integer.Should().NotBe(0);

        [Theory]
        [AutoData]
        public void Return_Autogenerated_Complex_Type_Object(Repository.Repository repository) => repository.Should().NotBeNull();

        [Theory]
        [InlineAutoData(1, 2)]
        public void Return_Autogenerated_Complex_Type_Object_And_Inline_Provided_Data(int firstInteger, int secondInteger, Repository.Repository repository)
        {
            firstInteger.Should().Be(1);
            secondInteger.Should().Be(2);
            repository.Should().NotBeNull();
        }
    }
}
